version: '3.8'

services:
  # Development service
  dev:
    build:
      context: .
      target: builder
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    environment:
      - NODE_ENV=development
    networks:
      - map-app-network

  # Production service
  prod:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - map-app-network

networks:
  map-app-network:
    driver: bridge 