name: Pull Request Checks

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  validate:
    name: Validate PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Validate commit messages
        uses: wagoid/commitlint-github-action@v5

      - name: Type check
        run: npm run build

      - name: Add PR Comment
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const { job, conclusion } = context.payload;
            const status = conclusion === 'success' ? '✅' : '❌';
            const body = `## Validation Results ${status}

            - Build: ${status}
            - Tests: ${status}
            - Commit Format: ${status}

            Please make sure your commits follow the [conventional commits](https://www.conventionalcommits.org/) format:
            \`\`\`
            feat(scope): add new feature
            fix(scope): fix some bug
            docs(scope): update documentation
            \`\`\`
            `;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });
